### ISSUE TITLE
Getting error after upgrading vscode

### ISSUE THREAD

**Issue by CreativeCactus** [vanessa-luna/banner-comments-plus#3]
```[2018-09-18 11:54:42.276] [exthost11] [error] TypeError: Path must be a string. Received undefined
	at assertPath (path.js:28:11)
	at Object.join (path.js:1251:7)
	at getLanguageConfig (/Users/user/.vscode/extensions/lunarlimbo.banner-comments-plus-0.3.1/out/extension.js:388:47)
	at getCommentConfig (/Users/user/.vscode/extensions/lunarlimbo.banner-comments-plus-0.3.1/out/extension.js:362:22)
	at getDefaultConfig (/Users/user/.vscode/extensions/lunarlimbo.banner-comments-plus-0.3.1/out/extension.js:358:24)
	at apply (/Users/user/.vscode/extensions/lunarlimbo.banner-comments-plus-0.3.1/out/extension.js:42:18)
	at e._executeContributedCommand (/private/var/folders/x3/z_xwpy9x16n796mf53mkdlzm0000gn/T/AppTranslocation/17513E2B-66EF-41B8-A9C7-B395D4B7EF5D/d/Visual Studio Code 2.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:712:994)
	at e.$executeContributedCommand (/private/var/folders/x3/z_xwpy9x16n796mf53mkdlzm0000gn/T/AppTranslocation/17513E2B-66EF-41B8-A9C7-B395D4B7EF5D/d/Visual Studio Code 2.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:713:479)
	at e._doInvokeHandler (/private/var/folders/x3/z_xwpy9x16n796mf53mkdlzm0000gn/T/AppTranslocation/17513E2B-66EF-41B8-A9C7-B395D4B7EF5D/d/Visual Studio Code 2.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:671:983)
	at e._invokeHandler (/private/var/folders/x3/z_xwpy9x16n796mf53mkdlzm0000gn/T/AppTranslocation/17513E2B-66EF-41B8-A9C7-B395D4B7EF5D/d/Visual Studio Code 2.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:671:701)
	at e._receiveRequest (/private/var/folders/x3/z_xwpy9x16n796mf53mkdlzm0000gn/T/AppTranslocation/17513E2B-66EF-41B8-A9C7-B395D4B7EF5D/d/Visual Studio Code 2.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:670:767)
	at e._receiveOneMessage (/private/var/folders/x3/z_xwpy9x16n796mf53mkdlzm0000gn/T/AppTranslocation/17513E2B-66EF-41B8-A9C7-B395D4B7EF5D/d/Visual Studio Code 2.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:670:536)
	at /private/var/folders/x3/z_xwpy9x16n796mf53mkdlzm0000gn/T/AppTranslocation/17513E2B-66EF-41B8-A9C7-B395D4B7EF5D/d/Visual Studio Code 2.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:669:452
	at /private/var/folders/x3/z_xwpy9x16n796mf53mkdlzm0000gn/T/AppTranslocation/17513E2B-66EF-41B8-A9C7-B395D4B7EF5D/d/Visual Studio Code 2.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:672:575
	at /private/var/folders/x3/z_xwpy9x16n796mf53mkdlzm0000gn/T/AppTranslocation/17513E2B-66EF-41B8-A9C7-B395D4B7EF5D/d/Visual Studio Code 2.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:96:903
	at e.fire (/private/var/folders/x3/z_xwpy9x16n796mf53mkdlzm0000gn/T/AppTranslocation/17513E2B-66EF-41B8-A9C7-B395D4B7EF5D/d/Visual Studio Code 2.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:98:218)
	at a (/private/var/folders/x3/z_xwpy9x16n796mf53mkdlzm0000gn/T/AppTranslocation/17513E2B-66EF-41B8-A9C7-B395D4B7EF5D/d/Visual Studio Code 2.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:162:713)
	at Socket._socketDataListener (/private/var/folders/x3/z_xwpy9x16n796mf53mkdlzm0000gn/T/AppTranslocation/17513E2B-66EF-41B8-A9C7-B395D4B7EF5D/d/Visual Studio Code 2.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:162:932)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at Pipe.onread (net.js:594:20) banner-comments-plus.Apply```

**Comment by vanessa-luna** [comment]
I apologize I never looked into these issues. I did not get notifications and never checked in..

Based on my out of date knowledge of my own codebase, this could be a unique situation with the languages you have installed in your code. I must not sanitize something I should. 

If I get around to updating the plugin I will add more error checking / santizing.
